id: IBEFC08C2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T02:15:11+00:00'
last_modified: '2022-06-08T07:21:08.612812+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4254
  title: སྐྱབས་འགྲོའི་རྣམ་བཤད་ལམ་བཟང་གསལ་བའི་ཉི་མ་སྡོམ་གསུམ་བདུད་རྩིའི་ཆུ་གཏེར་གཞན་སྟོང་བགྲོ་གླེང་ཐེངས་གཉིས་པའི་དྲིས་ལན་དཔག་བསམ་ལྗོན་ཤིང
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    FA92:
      image_group_id: I1KG4977
      title: ''
      total_pages: 308
      order: 1
      base_file: FA92.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
